### ISSUE TITLE
[FEATURE_REQ] Sync repo in Drawio

### ISSUE THREAD

**Issue by nickHttps** [SAP/btp-solution-diagrams#100]
### Area of the  BTP Solution Diagrams that should be enhanced?

Draw.io Templates

### Overview of feature request

Hi, first of all thanks for the great diagrams!

Would it be possible (or maybe you know how) to import the whole repo/folder into draw.io? At the moment I need to do:

1. File
2. Open Library
3. Select xml

Also it would keep things in sync by just pulling from main.

Thanks!

### Additional context

Drawio Desktop version

**Comment by fabianleh** [comment]
Hi @nickHttps , did you check the https://sap.github.io/btp-solution-diagrams/docs/solution_diagr_intro/intro/#add-sap-colors-btp-icons-logos-etc-to-drawio-configuration-at-once documentation.
I just updated now also the xml , with this you will be able to have all libs directly in draw.io:
<img width="1179" alt="image" src="https://github.com/SAP/btp-solution-diagrams/assets/91141653/4f1ee2d0-395f-4246-993c-e0a7a04ac8b5">

Did this help ?
