### ISSUE TITLE
Typos and missing links in page : Big Picture

### ISSUE THREAD

**Issue by Kaderde** [SAP/btp-solution-diagrams#101]
Hi, 
In https://sap.github.io/btp-solution-diagrams/docs/solution_diagr_intro/big_picture/
Under the TAM image, "Technical an detailed description of architectures" is missing a "d".

The starter kit can be obtained here. - missing link.

You can access the starter kit here. - missing link.

Thanks

Abdelkader

**Comment by fabianleh** [comment]
Hi @Kaderde , I just fixed the mentioned typo and missing links. Thx for letting us know...

best,
Fabian

**Comment by Kaderde** [comment]
Hi Fabian,

appreciate your quick response, 

Now it looks good :)

Best,
Abdelkader
