### ISSUE TITLE
[FEATURE_REQ] Add Link to GitHub page to "About Section"

### ISSUE THREAD

**Issue by lechnerc77** [SAP/btp-solution-diagrams#11]
**Is your feature request related to a problem? Please describe.**

Currently there is no obvious connection from the GitHub Repository to the generated GitHub Page. This makes navigating to the page although I have found the repository a bit cumbersome

**Describe the solution you'd like**

Add the link to the website area of the `About` section:

  ![image](https://github.com/SAP/btp-solution-diagrams/assets/22294087/fee532a8-f73f-4528-95c9-b53ec926c218)

  ![image](https://github.com/SAP/btp-solution-diagrams/assets/22294087/003e9329-0337-493d-aa4d-455845634d75)

**Describe alternatives you've considered**

n/a

**Additional context**

n/a

**Comment by fabianleh** [comment]
Good point !
