### ISSUE TITLE
[FEATURE_REQ] Cloud Application Programming Model (CAP) as Icon

### ISSUE THREAD

**Issue by kay-schmitteckert** [SAP/btp-solution-diagrams#113]
### Area of the  BTP Solution Diagrams that should be enhanced?

Starter Kit

### Overview of feature request

Please create an icon for Cloud Application Programming Model (CAP)

### Additional context

https://cap.cloud.sap/docs/

**Comment by fabianleh** [comment]
Hi @kay-schmitteckert , we'll add this to the backlog for the next update. best, Fabian

**Comment by fabianleh** [comment]
@kay-schmitteckert , Icon confirmed will be available in the next update for BTP Service Icons.

best,
Fabian
