### ISSUE TITLE
Please make icons for *ALL* BTP services available both in ppt template and draw.io 🤝

### ISSUE THREAD

**Issue by iamashokkumar** [SAP/btp-solution-diagrams#122]
### Area of the  BTP Solution Diagrams that should be enhanced?

Starter Kit

### Overview of feature request

Please make icons for all BTP services available both in ppt template and draw.io.

Recently I was creating a BTP architecture and I could not find icons for SAP Integration Suite, Forms by Adobe etc.,

**Comment by fabianleh** [comment]
Hi @iamashokkumar , our focus is support more the diagramming tools draw.io and Lucidchart, but you can make ue of the [SVG's](https://github.com/SAP/btp-solution-diagrams/tree/main/assets/shape-libraries-and-editable-presets/svg)
For the next release of the PPT templates we'll discuss if we provide in the future more examples and icons also for PPT.

thx and best,
Fabian

**Comment by iamashokkumar** [comment]
having all BTP services icons both in PPT and draw.io would help everyone a lot. Hopefully we get there in the next release. Thanks
