### ISSUE TITLE
[FEATURE_REQ] Provide draw.io libraries and samples as release artefacts

### ISSUE THREAD

**Issue by mpern** [SAP/btp-solution-diagrams#13]
### Area of the  BTP Solution Diagrams that should be enhanced?

Starter Kit

### Overview of feature request

It would be great if I could simply download a zip with all libraries, another zip with samples etc. instead if needing to download the files one by one from the respective [starter kit page](https://github.com/SAP/btp-solution-diagrams/tree/main/assets/shape-libraries-and-editable-presets/draw.io)

Ideally, all the libraries, samples etc are averrable as "Assets" of a [release](https://github.com/SAP/btp-solution-diagrams/releases)

### Proposed solution

- bundle draw.io libraries in a zip
- bundle samples in a zip
- publish as "asset" of a release

**Comment by lechnerc77** [comment]
@mpern This feature is now enabled. You find the first execution in the [latest release](https://github.com/SAP/btp-solution-diagrams/releases/tag/btpsd-v1.0.1)
