### ISSUE TITLE
[BUG] Incorrect title for Fieldglass it is set as Fieldgrass

### ISSUE THREAD

**Issue by katansapdevelop** [SAP/btp-solution-diagrams#131]
### Main area of the  BTP Solution Diagrams that is affected?

Draw.io Templates

### Steps to reproduce

Under "SAP/Products" the label shows as Fieldgrass 

![image](https://github.com/user-attachments/assets/3ce6f309-9e63-4884-9b6c-0c50f9d07e1c)

### Observed behavior

When the component is added to a diagram you can see it is incorrectly labelled
![image](https://github.com/user-attachments/assets/9a85768d-99fb-4d9c-ab73-99e70dcbe501)

### Desired behavior

The label should be "Fieldglass"

**Comment by fabianleh** [comment]
Hi @katansapdevelop, yes correct I see also the typo in the "native" draw.io integration. The library provided here do not have the typo, pleas double check: https://github.com/SAP/btp-solution-diagrams/blob/main/assets/shape-libraries-and-editable-presets/draw.io/SAP_Products_SAP_BTP.xml
We need to create an issue here: https://github.com/jgraph/drawio/issues
It's possible to create this issue or should I do?

**Comment by fabianleh** [comment]
@katansapdevelop Thx for creating an issue at the "jgraph" git. I'll add the link here as well:
https://github.com/jgraph/drawio/issues/4596

**Comment by fabianleh** [comment]
Hi @katansapdevelop , it's solved with drawio 24.7.8
