### ISSUE TITLE
[BUG] `Numbers_SAP_BTP` draw.io assets have issue with style settings

### ISSUE THREAD

**Issue by levinanton** [SAP/btp-solution-diagrams#146]
### Main area of the  BTP Solution Diagrams that is affected?

Draw.io Templates

### Steps to reproduce

1. Get latest `assets/shape-libraries-and-editable-presets/draw.io/Numbers_SAP_BTP.xml` -> [0322402d169414cd59333408bbaeceff0ab84081](https://github.com/SAP/btp-solution-diagrams/commit/ed43a1af26e3853cc5817fcb9a91a8a429d6417e)
2. Import as Library into draw.io `v24.7.8` (for macOS) https://github.com/jgraph/drawio-desktop/releases
3. Add any number on a canvas

![Screenshot 2024-09-18 at 07 19 05](https://github.com/user-attachments/assets/e5d80056-cab8-45f0-a6bb-15a4b48e2b7b)

### Observed behavior

It turns out that numbers (texts) have wrongs background color, wrong margins and positioning (according to its bubble)

![Screenshot 2024-09-18 at 07 24 43](https://github.com/user-attachments/assets/085c67c5-5277-42a7-8876-94240edf243e)

### Desired behavior

Expecting to get correct styling out of the box:

![Screenshot 2024-09-18 at 07 26 54](https://github.com/user-attachments/assets/34c7caf2-52c6-48f5-bdfa-08cc73555563)

**Comment by fabianleh** [comment]
Hi @levinanton , for me it works tested with version v24.7.8 : 
<img width="361" alt="image" src="https://github.com/user-attachments/assets/49a7d498-791f-457b-a2d2-2b72ffbaa5cc">

Also by unsing the embedded library integration works:
<img width="312" alt="image" src="https://github.com/user-attachments/assets/9c6e71cc-f348-4130-9b13-c64cbaf6f708">

Can you pls. doublecheck?

**Comment by levinanton** [comment]
@fabianleh interesting. I have added a new blank page (in the same draw.io file), added a number there and it rendered w/o issues. Closed that page and continued with my current page. Adding numbers there now works w/o issues there as well.

![Screenshot 2024-09-18 at 11 01 46](https://github.com/user-attachments/assets/ecdda696-6e11-4c79-80f9-b9618b405858)

Sorry for panic. We may close this issue.

**Comment by fabianleh** [comment]
Let's closed for now
