### ISSUE TITLE
[FEATURE_REQ] An icon for BTP Document Management Service appears to be missing from the library

### ISSUE THREAD

**Issue by neilprince** [SAP/btp-solution-diagrams#164]
An icon for BTP Document Management Service appears to be missing from the library

**Comment by neilprince** [comment]
I noticed it is in the library for large icons but not medium icons

**Comment by neilprince** [comment]
In addition, there is no icon for the saas-registry service

**Comment by fabianleh** [comment]
@neilprince : Missing service is now added as part of the "foundational" lib: https://github.com/SAP/btp-solution-diagrams/tree/main/assets/shape-libraries-and-editable-presets/draw.io/20-02-00-sap-btp-service-icons-foundational-set
