### ISSUE TITLE
[FEATURE_REQ] add service icon for DOX

### ISSUE THREAD

**Issue by lirudayam** [SAP/btp-solution-diagrams#23]
### Area of the  BTP Solution Diagrams that should be enhanced?

Starter Kit

### Overview of feature request

Hello, I'm missing the service icon for Document Information Extraction :-)

**Comment by fabianleh** [comment]
Ho @lirudayam ,

thx for the info and yes you're right this icon was missed in the library for draw.io.
Just added this an created a new release: https://github.com/SAP/btp-solution-diagrams/releases/tag/btpsd-v1.0.4

Best,
Fabian
