### ISSUE TITLE
[FEATURE_REQ] add service icon for SAP Cloud Identity Authentication + SAP Cloud ALM

### ISSUE THREAD

**Issue by piejanssens** [SAP/btp-solution-diagrams#8]
I used [this AIO setup](https://github.com/SAP/btp-solution-diagrams/blob/main/guideline/docs/examples/drawio-config-all-in-one.json). I cannot find any icon for CALM or IAS.

**Comment by fabianleh** [comment]
Hi @piejanssens , thx for the feedback in the provide library ([xml](https://github.com/SAP/btp-solution-diagrams/blob/main/assets/shape-libraries-and-editable-presets/draw.io/Service_Icons_SAP_BTP.xml)) IAS and IPS are included: 
<img width="451" alt="image" src="https://github.com/SAP/btp-solution-diagrams/assets/91141653/d88c8f97-5598-4861-8a3f-ca2513778718">
Can you please check on your side as well ?

thx and best, Fabian

**Comment by fabianleh** [comment]
@piejanssens I try to fix the AIO config in the next days. 
For the topic of Cloud ALM I will check and come back asap.

best,
Fabian
