### ISSUE TITLE
[FEATURE_REQ] Add icon for the SAP Cloud Connector

### ISSUE THREAD

**Issue by arturo-florez** [SAP/btp-solution-diagrams#81]
### Area of the  BTP Solution Diagrams that should be enhanced?

Starter Kit

### Overview of feature request

Please add an icon for the SAP Cloud Connector. This is an integral part of the architecture setup when connecting on-premise systems. In previous versions there used to be an icon for this component.

### Proposed solution

Add an icon for SAP Cloud Connector

### Additional context

Info about Cloud Connector:
https://help.sap.com/docs/connectivity/sap-btp-connectivity-cf/cloud-connector

**Comment by fabianleh** [comment]
Hi @arturo-florez ,

we will provide an icon for SAP Cloud Connector soon ... stay tuned.

best,
Fabian
